site_name: My Docs

theme:
  name: material
  language: ja
  font: # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
    text: Noto Sans JP
    code: JetBrains Mono
  features:
    - navigation.instant     ## mkdocs for MaterialのSPA対応
    - navigation.tabs        ## トップレベル項目を画面上部メニューにタブ表示
    ##- navigation.sections  ## 項目のセクション表示 
    ##- navigation.expand    ## 初期表示で全てのページ展開を有効化
    - navigation.top       ## ページTOP遷移ボタンを有効化
    - toc.integrate        ## 画面左右のメニューを統

nav:
  - 概要: index.md
  - Blog: blog/index.md

markdown_extensions:
  # 目次
  - toc:
      # 自動生成を有効にする
      permalink: true
      # 目次の上に表示する文言
      title: 見出し
      # 見出しにする深さ
      toc_depth: 3
  # コードハイライトの設定（デフォルトのcodehiliteを使わずに拡張機能を使用）
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - attr_list # for emoji and etc...
  - meta # for navigation and etc...
  - pymdownx.details # for admonition
  - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        # https://squidfunk.github.io/mkdocs-material/reference/diagrams/
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  # 検索機能
  - search:
      lang: ja
      # インデックス対象の条件
      separator: '[\s\-\.]'
      # 各ページのタイトル、セクション見出し、および全文にインデックスを付けます。
      indexing: 'full'
#   # https://liang2kl.codes/mkdocs-blogging-plugin/
  - blogging:
      dirs:
        - blog
      size: 10
      locale: ja_JP
      features:
        tags: {}
  - git-revision-date-localized:
      type: custom
      custom_format: "%Y/%m/%d %H:%M"
      timezone: Asia/Tokyo
      exclude:
        - index.md
        - blog/index.md

site_url: https://0521nao80.github.io/mkdocs/blog/
